import React, { Component } from 'react';
import {
    AppRegistry, View, Image, Text, TouchableOpacity, StyleSheet, TextInput,
    ScrollView, Alert, AsyncStorage, ToastAndroid, ListView, ActivityIndicator, Dimensions
} from 'react-native';
import {
    Container, Content, Badge, Row, Header, Title, Button, Tabs, Tab, Fab, Footer, FooterTab,
    Right, Left, Body, TabHeading, Radio
} from 'native-base';
import Constant from "../Constant"
var width = Dimensions.get('window').width; //full width
var height = Dimensions.get('window').height; //full height

export default class Categories extends Component {
    //hide default header generated by stacknavigator
    static navigationOptions = {
        header: null
        //headerMode: 'none'
    };



    render() {
        return (
            <View style={styles.container} >

                <Header hasTabs
                    style={{ backgroundColor: Constant.primaryColor, justifyContent: 'center', }}
                    androidStatusBarColor={Constant.androidStatusBarColor}
                    iosBarStyle="light-content">

                    <View style={{ width: width, flexDirection: "row", alignItems: 'center', justifyContent: 'center', }}>

                        <TouchableOpacity onPress={() => this.props.navigation.navigate("Home")}
                            style={{ marginLeft: 10, position: 'absolute', left: 0, }}>
                            <Image source={require('../images/icon/new/toggle.png')} style={{ width: 24, height: 24 }} />
                        </TouchableOpacity>
                        <Text style={{ fontWeight: 'bold', color: "#FFF", fontSize: 22, position: 'absolute', }}>
                            Categories</Text>


                    </View>
                </Header>
                <View style={{
                    backgroundColor: '#FFFFFF', marginLeft: 5, marginRight: 5, borderRadius: 10,
                    height: 40, marginTop: 10
                }}>
                    <TextInput secureTextEntry={this.props.secureTextEntry} placeholder={"SEARCH PRODUCTS"}
                        placeholderTextColor="gray" underlineColorAndroid={'transparent'}
                        style={{ marginLeft: 10 }}
                        textColor="#000" />

                    <TouchableOpacity style={{
                        position: "absolute", right: 5, top: 10, alignItems: 'center',
                        backgroundColor: Constant.primaryColor, marginRight: 10, width: 50, height: 25, borderRadius: 20
                    }}>
                        <Image style={{ resizeMode: "contain", width: 15, height: 15, marginTop: 4 }} source={require('../images/search.png')} />
                    </TouchableOpacity>
                </View>

                <ScrollView>
                    <View style={{
                        marginTop: 25, marginLeft: 20, marginRight: 20
                    }}>
                        <View style={{
                            justifyContent: 'space-between', backgroundColor: 'transparent',
                            flexDirection: 'row', marginTop: 5,
                        }}>
                            <View style={{ alignItems: 'center', marginLeft: 20 }}>
                                <TouchableOpacity onPress={() => this.props.navigation.navigate("Login")}
                                   style={{
                                         
                                    backgroundColor: 'transparent', 
                                }} >
                                    <Image source={require("../images/icon/new/transport.png")} style={styles.iconContainer} />

                                </TouchableOpacity>
                                <Text style={{ fontWeight: 'bold', color: "lightgray", fontSize: 15, marginTop: 10 }}>
                                    Transport</Text>
                            </View>
                            <View style={{ alignItems: 'center', }}>
                                <TouchableOpacity onPress={() => this.props.navigation.navigate("Food")}
                                   style={{
                                         
                                    backgroundColor: 'transparent', 
                                }} >
                                    <Image source={require("../images/icon/new/food.png")} style={styles.iconContainer} />

                                </TouchableOpacity>
                                <Text style={{ fontWeight: 'bold', color: "lightgray", fontSize: 15, marginTop: 10 }}>
                                    Food</Text>
                            </View>
                            <View style={{ alignItems: 'center', marginRight: 20 }}>
                                <TouchableOpacity onPress={() => this.props.navigation.navigate("Login")}
                                   style={{
                                         
                                    backgroundColor: 'transparent', 
                                }} >
                                    <Image source={require("../images/icon/new/bill.png")} style={styles.iconContainer} />

                                </TouchableOpacity>
                                <Text style={{ fontWeight: 'bold', color: "lightgray", fontSize: 15, marginTop: 10 }}>
                                    Bills</Text>
                            </View>

                        </View>

                        <View style={{
                            justifyContent: 'space-between', backgroundColor: 'transparent',
                            flexDirection: 'row', marginTop: 40,
                        }}>
                            <View style={{ alignItems: 'center', marginLeft: 20 }}>
                                <TouchableOpacity onPress={() => this.props.navigation.navigate("Login")}
                                   style={{
                                         
                                    backgroundColor: 'transparent', 
                                }} >
                                    <Image source={require("../images/icon/new/home.png")} style={styles.iconContainer} />

                                </TouchableOpacity>
                                <Text style={{ fontWeight: 'bold', color: "lightgray", fontSize: 15, marginTop: 10 }}>
                                    Home</Text>
                            </View>
                            <View style={{ alignItems: 'center', }}>
                                <TouchableOpacity onPress={() => this.props.navigation.navigate("Login")}
                                    style={{
                                         
                                        backgroundColor: 'transparent', 
                                    }} >
                                    <Image source={require("../images/icon/new/pets.png")} style={styles.iconContainer} />

                                </TouchableOpacity>
                                <Text style={{ fontWeight: 'bold', color: "lightgray", fontSize: 15, marginTop: 10 }}>
                                    Pets</Text>
                            </View>
                            <View style={{ alignItems: 'center', marginRight: 20 }}>
                                <TouchableOpacity onPress={() => this.props.navigation.navigate("Login")}
                                    style={{
                                         
                                        backgroundColor: 'transparent', 
                                    }} >
                                    <Image source={require("../images/icon/new/education.png")} style={styles.iconContainer} />

                                </TouchableOpacity>
                                <Text style={{ fontWeight: 'bold', color: "lightgray", fontSize: 15, marginTop: 10 }}>
                                    Education</Text>
                            </View>

                        </View>

                        <View style={{
                            justifyContent: 'space-between', backgroundColor: 'transparent',
                            flexDirection: 'row', marginTop: 40,
                        }}>
                            <View style={{ alignItems: 'center', marginLeft: 20 }}>
                                <TouchableOpacity onPress={() => this.props.navigation.navigate("Login")}
                                    style={{
                                         
                                        backgroundColor: 'transparent', 
                                    }} >
                                    <Image source={require("../images/icon/new/beauty.png")} style={styles.iconContainer} />

                                </TouchableOpacity>
                                <Text style={{ fontWeight: 'bold', color: "lightgray", fontSize: 15, marginTop: 10 }}>
                                    Beauty</Text>
                            </View>
                            <View style={{ alignItems: 'center', }}>
                                <TouchableOpacity onPress={() => this.props.navigation.navigate("Login")}
                                   style={{
                                         
                                    backgroundColor: 'transparent', 
                                }} >
                                    <Image source={require("../images/icon/new/kids.png")} style={styles.iconContainer} />

                                </TouchableOpacity>
                                <Text style={{ fontWeight: 'bold', color: "lightgray", fontSize: 15, marginTop: 10 }}>
                                    Kids</Text>
                            </View>
                            <View style={{ alignItems: 'center', marginRight: 20 }}>
                                <TouchableOpacity onPress={() => this.props.navigation.navigate("Login")}
                                    style={{
                                         
                                        backgroundColor: 'transparent', 
                                    }} >
                                    <Image source={require("../images/icon/new/healthcare.png")} style={styles.iconContainer} />

                                </TouchableOpacity>
                                <Text style={{ fontWeight: 'bold', color: "lightgray", fontSize: 15, marginTop: 10 }}>
                                    Healthcare</Text>
                            </View>

                        </View>
                    </View>
                </ScrollView>

                <Footer style={styles.footer} >

                    <View style={{
                        width: width, justifyContent: 'space-between', backgroundColor: Constant.bottomTab,
                        flexDirection: 'row', alignItems: 'center'
                    }}>
                        <View style={{ alignItems: 'center', marginLeft: 20 }}>
                            <TouchableOpacity
                            >
                                <Image source={require("../images/icon/new/icon1.png")} style={styles.iconContainerBot} />
                            </TouchableOpacity>
                        </View>
                        <View style={{ alignItems: 'center' }}>
                            <TouchableOpacity
                            >
                                <Image source={require("../images/icon/new/icon2.png")} style={styles.iconContainerBot} />
                            </TouchableOpacity>
                        </View>
                        <View style={{ alignItems: 'center' }}>
                            <TouchableOpacity
                            >
                                <Image source={require("../images/icon/camera.png")} style={styles.iconContainerBot} />
                            </TouchableOpacity>
                        </View>
                        <View style={{ alignItems: 'center', marginRight: 20 }}>
                            <TouchableOpacity
                            >
                                <Image source={require("../images/icon/new/icon3.png")} style={styles.iconContainerBot} />
                            </TouchableOpacity>
                        </View>

                    </View>
                </Footer>
            </View>
        );
    }
}


const styles = StyleSheet.create({
    container: {
        backgroundColor: "#F7F6FB",
        height: '100%',
    },
    buttonOnBed: {
        marginBottom: 10,
        marginLeft: 20,
        marginTop: 15,
        flexDirection: 'row'
    },
    iconContainer: {
        height: 70, width: 70, borderRadius: 35,
    },
    iconContainerBot: {
        height: 35, width: 35,  
    },
    footer: {
        position: 'absolute',
        height: 50,
        bottom: 0,
        backgroundColor: Constant.bottomTab
    },
})