import React, { Component } from 'react';
import {
    AppRegistry, View, Image, Text, TouchableOpacity, StyleSheet, TextInput,
    ScrollView, Alert, AsyncStorage, ToastAndroid, ListView, ActivityIndicator, Dimensions, Picker
} from 'react-native';
import {
    Container, Content, Badge, Row, Header, Title, Button, Tabs, Tab, Fab, Footer, FooterTab,
    Right, Left, Body, TabHeading, Radio, CheckBox
} from 'native-base';
import Constant from "../Constant"
var width = Dimensions.get('window').width; //full width
var height = Dimensions.get('window').height; //full height

const datas = [
    {
        item1: "Cheese",
        item2: "Mayo",
        id: 1
    },
    {
        item1: "Lettuce",
        item2: "Ketchup",
        id: 2
    },
    {
        item1: "Tomato",
        item2: "Mustard",
        id: 3
    },
    {
        item1: "Onion",
        item2: "Pikle",
        id: 4
    },
];

export default class Food extends Component {
    //hide default header generated by stacknavigator
    static navigationOptions = {
        header: null
        //headerMode: 'none'
    };
    constructor(props) {
        super(props)

        this.state = {
            isSelected: false,
            show: false, show1: false, checked1: false, checked2: false,
            isVisible: false, isVisible1: false,
        }
    }

    toggle1() {
        if (this.state.isVisible1) {
            this.setState({
                isVisible1: false
            });
        } else {
            this.setState({
                isVisible1: true
            });
        }
    }
    toggle() {
        if (this.state.isVisible) {
            this.setState({
                isVisible: false
            });
        } else {
            this.setState({
                isVisible: true
            });
        }
    }


    onShow1 = () => {
        this.toggle1()
        if (this.state.show1 == false) {
            this.setState({
                show1: true
            })
        } else {
            this.setState({
                show1: false
            })
        }
    }
    onShow = () => {
        this.toggle()
        if (this.state.show == false) {
            this.setState({
                show: true
            })
        } else {
            this.setState({
                show: false
            })
        }
    }

    render() {
        const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 })
        return (
            <View style={styles.container} >

                <Header hasTabs
                    style={{ backgroundColor: Constant.primaryColor, justifyContent: 'center', }}
                    androidStatusBarColor={Constant.androidStatusBarColor}
                    iosBarStyle="light-content">

                    <View style={{ width: width, flexDirection: "row", alignItems: 'center', justifyContent: 'center', }}>

                        <TouchableOpacity onPress={() => this.props.navigation.navigate("Categories")}
                            style={{ marginLeft: 10, position: 'absolute', left: 0, }}>
                            <Image source={require('../images/icon/new/toggle.png')} style={{ width: 24, height: 24 }} />
                        </TouchableOpacity>
                        <Text style={{ fontWeight: 'bold', color: "#FFF", fontSize: 22, position: 'absolute', }}>
                            Food</Text>


                    </View>
                </Header>
                <View style={{
                    backgroundColor: '#FFFFFF', marginLeft: 5, marginRight: 5, borderRadius: 10,
                    height: 40, marginTop: 10
                }}>
                    <TextInput secureTextEntry={this.props.secureTextEntry} placeholder={"SEARCH PRODUCTS"}
                        placeholderTextColor="gray" underlineColorAndroid={'transparent'}
                        style={{ marginLeft: 10 }}
                        textColor="#000" />

                    <TouchableOpacity style={{
                        position: "absolute", right: 5, top: 10, alignItems: 'center',
                        backgroundColor: Constant.primaryColor, marginRight: 10, width: 50, height: 25, borderRadius: 20
                    }}>
                        <Image style={{ resizeMode: "contain", width: 15, height: 15, marginTop: 4 }} source={require('../images/search.png')} />
                    </TouchableOpacity>
                </View>

                <ScrollView>
                    <View style={{
                        width: width, marginTop: 25, marginBottom: 120,
                    }}>

                        <View style={{ alignItems: 'center', flexDirection: 'row', marginTop: 25 }}>
                            <View style={{ flexDirection: 'row', alignItems: 'center', }}>

                                <View
                                    style={{
                                        alignItems: 'center', flexDirection: 'row',
                                    }} >

                                    <View style={{ alignItems: 'center', marginLeft: 15 }}>
                                        <Image source={require('../images/no.png')}

                                            style={{
                                                width: 35, height: 35, borderRadius: 16
                                            }} >
                                        </Image>
                                    </View>
                                    <View style={{ marginLeft: 15, }}>
                                        <Text style={{ fontWeight: 'bold', color: "gray", fontSize: 16, }}>
                                            Hot Dog</Text>
                                        <Text style={{ color: "gray", fontSize: 16, }}>
                                            $7.86</Text>
                                    </View>
                                </View>
                            </View>

                            <View style={{ position: 'absolute', right: 10, justifyContent: 'center', }}>
                                <TouchableOpacity  >
                                    <View style={styles.button1}>
                                        <Image
                                            style={styles.indicator}
                                            source={require("../images/icon/plus.png")}
                                        />
                                    </View>
                                </TouchableOpacity>
                            </View>
                        </View>


                        <View style={{ marginTop: 15, alignItems: 'center', flexDirection: 'row' }}>
                            <View style={{ flexDirection: 'row', alignItems: 'center', }}>

                                <View
                                    style={{
                                        alignItems: 'center', flexDirection: 'row',
                                    }} >

                                    <View style={{ alignItems: 'center', marginLeft: 15 }}>
                                        <Image source={require('../images/no.png')}

                                            style={{
                                                width: 35, height: 35, borderRadius: 16
                                            }} >
                                        </Image>
                                    </View>
                                    <View style={{ marginLeft: 15, }}>
                                        <Text style={{ fontWeight: 'bold', color: "gray", fontSize: 16, }}>
                                            Hot Dog</Text>
                                        <Text style={{ color: "gray", fontSize: 16, }}>
                                            $7.86</Text>
                                    </View>
                                </View>
                            </View>

                            <View style={{ position: 'absolute', right: 10, justifyContent: 'center', }}>
                                <TouchableOpacity onPress={this.onShow1}>
                                    <View style={styles.button1}>
                                        {this.state.isVisible1 && (
                                            <Image
                                                style={styles.indicator}
                                                source={require('../images/icon/chevron-down.png')}
                                            />
                                        )}
                                        {!this.state.isVisible1 && (
                                            <Image
                                                style={styles.indicator}
                                                source={require('../images/icon/plus.png')}
                                            />
                                        )}
                                    </View>
                                </TouchableOpacity>
                            </View>
                        </View>
                        {this.state.show1 && <View style={{}}>

                            <View>

                                <View style={{ alignItems: 'center', flexDirection: 'row', marginTop: 25 }}>
                                    <View style={{ flexDirection: 'row', alignItems: 'center', }}>

                                        <View
                                            style={{
                                                alignItems: 'center', flexDirection: 'row',
                                            }} >

                                            <View style={{ alignItems: 'center', marginLeft: 15 }}>

                                            </View>
                                            <View style={{ marginLeft: 15, }}>
                                                <Text style={{ fontWeight: 'bold', color: "gray", fontSize: 16, }}>
                                                    Small</Text>
                                                <Text style={{ color: "gray", fontSize: 16, }}>
                                                    $7.86</Text>
                                            </View>
                                        </View>
                                    </View>

                                    <View style={{ position: 'absolute', right: 10, justifyContent: 'center', }}>
                                        <TouchableOpacity >
                                            <View style={styles.button1}>
                                                <Image
                                                    style={styles.indicator}
                                                    source={require("../images/icon/plus.png")}
                                                />
                                            </View>
                                        </TouchableOpacity>
                                    </View>
                                </View>
                                <View style={{ alignItems: 'center', flexDirection: 'row', marginTop: 25 }}>
                                    <View style={{ flexDirection: 'row', alignItems: 'center', }}>

                                        <View
                                            style={{
                                                alignItems: 'center', flexDirection: 'row',
                                            }} >

                                            <View style={{ alignItems: 'center', marginLeft: 15 }}>

                                            </View>
                                            <View style={{ marginLeft: 15, }}>
                                                <Text style={{ fontWeight: 'bold', color: "gray", fontSize: 16, }}>
                                                    Medium</Text>
                                                <Text style={{ color: "gray", fontSize: 16, }}>
                                                    $7.86</Text>
                                            </View>
                                        </View>
                                    </View>

                                    <View style={{ position: 'absolute', right: 10, justifyContent: 'center', }}>
                                        <TouchableOpacity>
                                            <View style={styles.button1}>
                                                <Image
                                                    style={styles.indicator}
                                                    source={require("../images/icon/plus.png")}
                                                />
                                            </View>
                                        </TouchableOpacity>
                                    </View>
                                </View>


                            </View>
                        </View>}

                        <View style={{ marginTop: 15, alignItems: 'center', flexDirection: 'row' }}>
                            <View style={{ flexDirection: 'row', alignItems: 'center', }}>

                                <View
                                    style={{
                                        alignItems: 'center', flexDirection: 'row',
                                    }} >

                                    <View style={{ alignItems: 'center', marginLeft: 15 }}>
                                        <Image source={require('../images/no.png')}

                                            style={{
                                                width: 35, height: 35, borderRadius: 16
                                            }} >
                                        </Image>
                                    </View>
                                    <View style={{ marginLeft: 15, }}>
                                        <Text style={{ fontWeight: 'bold', color: "gray", fontSize: 16, }}>
                                            Hot Dog</Text>
                                        <Text style={{ color: "gray", fontSize: 16, }}>
                                            $7.86</Text>
                                    </View>
                                </View>
                            </View>

                            <View style={{ position: 'absolute', right: 10, justifyContent: 'center', }}>
                                <TouchableOpacity onPress={this.onShow}>
                                    <View style={styles.button1}>
                                        {this.state.isVisible && (
                                            <Image
                                                style={styles.indicator}
                                                source={require('../images/icon/chevron-down.png')}
                                            />
                                        )}
                                        {!this.state.isVisible && (
                                            <Image
                                                style={styles.indicator}
                                                source={require('../images/icon/plus.png')}
                                            />
                                        )}
                                    </View>
                                </TouchableOpacity>
                            </View>
                        </View>
                        {this.state.show && <View style={{}}>

                            <View>

                                <ListView
                                    enableEmptySections={true}
                                    dataSource={ds.cloneWithRows(datas)}
                                    renderRow={(rowData) =>
                                        <View style={{
                                            alignItems: 'center', flexDirection: 'row',
                                            justifyContent: 'space-around', marginTop: 20
                                        }}>
                                            <View style={{ width: 100, marginLeft: 20, flexDirection: 'row', alignItems: 'center', }}>

                                                <CheckBox color="gray"
                                                    onPress={() => this.setState({ checked1: !this.state.checked1 })}
                                                    checked={this.state.checked1} />
                                                <Text style={{ color: "#000", fontSize: 16, marginLeft: 20 }}>
                                                    {rowData.item1}</Text>
                                            </View>

                                            <View style={{ width: 100, marginRight: 20, flexDirection: 'row', alignItems: 'center', marginLeft: 20 }}>


                                                <CheckBox color="gray"
                                                    onPress={() => this.setState({ checked2: !this.state.checked2 })}
                                                    checked={this.state.checked2} />
                                                <Text style={{ color: "#000", fontSize: 16, marginLeft: 20 }}>
                                                    {rowData.item2}</Text>
                                            </View>
                                        </View>
                                    } />


                            </View>
                        </View>}

                        <View style={{ marginTop: 15, alignItems: 'center', flexDirection: 'row' }}>
                            <View style={{ flexDirection: 'row', alignItems: 'center', }}>

                                <View
                                    style={{
                                        alignItems: 'center', flexDirection: 'row',
                                    }} >

                                    <View style={{ alignItems: 'center', marginLeft: 15 }}>
                                        <Image source={require('../images/no.png')}

                                            style={{
                                                width: 35, height: 35, borderRadius: 16
                                            }} >
                                        </Image>
                                    </View>
                                    <View style={{ marginLeft: 15, }}>
                                        <Text style={{ fontWeight: 'bold', color: "gray", fontSize: 16, }}>
                                            Hot Dog</Text>
                                        <Text style={{ color: "gray", fontSize: 16, }}>
                                            $7.86</Text>
                                    </View>
                                </View>
                            </View>

                            <View style={{ position: 'absolute', right: 10, justifyContent: 'center', }}>
                                <TouchableOpacity  >
                                    <View style={styles.button1}>
                                        <Image
                                            style={styles.indicator}
                                            source={require("../images/icon/plus.png")}
                                        />
                                    </View>
                                </TouchableOpacity>
                            </View>
                        </View>



                    </View>
                </ScrollView>

                <Footer style={styles.footer} >

                <View style={{
                    width: width, justifyContent: 'space-between', backgroundColor: Constant.bottomTab,
                    flexDirection: 'row', alignItems: 'center'
                }}>
                    <View style={{ alignItems: 'center', marginLeft: 20 }}>
                        <TouchableOpacity
                        >
                            <Image source={require("../images/icon/new/icon1.png")} style={styles.iconContainerBot} />
                        </TouchableOpacity>
                    </View>
                    <View style={{ alignItems: 'center' }}>
                        <TouchableOpacity
                        >
                            <Image source={require("../images/icon/new/icon2.png")} style={styles.iconContainerBot} />
                        </TouchableOpacity>
                    </View>
                    <View style={{ alignItems: 'center' }}>
                        <TouchableOpacity
                        >
                            <Image source={require("../images/icon/camera.png")} style={styles.iconContainerBot} />
                        </TouchableOpacity>
                    </View>
                    <View style={{ alignItems: 'center', marginRight: 20 }}>
                        <TouchableOpacity
                        >
                            <Image source={require("../images/icon/new/icon3.png")} style={styles.iconContainerBot} />
                        </TouchableOpacity>
                    </View>

                </View>
            </Footer>
            </View>
        );
    }
}


const styles = StyleSheet.create({
    container: {
        backgroundColor: "#F7F6FB",
        height: '100%',
    },
    buttonOnBed: {
        marginBottom: 10,
        marginLeft: 20,
        marginTop: 15,
        flexDirection: 'row'
    },
    iconContainerBot: {
        height: 35, width: 35,  
    },
    footer: {
        position: 'absolute',
        height: 50,
        bottom: 0,
        backgroundColor: Constant.bottomTab
    },
    indicator: {
        width: 35,
        height: 35,
        resizeMode: "contain",
    },
})